sudo: required
dist: precise
language: cpp
notifications:
  email: false
env:
- CORPUS_TEST_DIR=/home/travis/build/alekskivuls/arXivSearchEngine/test/documents/testCorpus
before_install:
- sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test 
- sudo apt-add-repository -y ppa:george-edison55/precise-backports
- sudo apt-add-repository --yes ppa:boost-latest/ppa
- sudo sh -c 'echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" >> /etc/apt/sources.list'
- sudo apt-get update -qq
- pip install --user cpp-coveralls
install:
- sudo apt-get install -y libboost1.55-all-dev cmake cmake-data valgrind g++-5 gcc-5
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 30
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 20
script:
- mkdir build
- cd build
- cmake ..
- make
- ctest
- ./arXivSearchEngine_test
- cd ..
after_success:
- coveralls --exclude lib --exclude tests --gcov-options '\-lp'
- sudo apt-get install doxygen graphviz
- openssl aes-256-cbc
  -K $encrypted_7c35d333d4f9_key
  -iv $encrypted_7c35d333d4f9_iv
  -in config/travisci_rsa.enc
  -out config/travisci_rsa
  -d
- chmod 0600 config/travisci_rsa
- cp config/travisci_rsa ~/.ssh/id_rsa
- chmod u+x ./config/publish-doxygen
- ./config/publish-doxygen
