language: cpp
addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
            - george-edison55-precise-backports
            - boost-latest/ppa
          packages:
            - clang-3.8
            - cmake
            - cmake-data
            - g++-4.8 
            - libboost1.55-all-dev
script:
- mkdir build
- cd build
- cmake ..
- make
- cd ..
after_success:
- sudo apt-get install doxygen graphviz
- openssl aes-256-cbc
  -K $encrypted_7c35d333d4f9_key
  -iv $encrypted_7c35d333d4f9_iv
  -in config/travisci_rsa.enc
  -out config/travisci_rsa
  -d
- chmod 0600 config/travisci_rsa
- cp config/travisci_rsa ~/.ssh/id_rsa
- chmod u+x ./config/publish-doxygen
- ./config/publish-doxygen
